# Written to be available, and tested that it works, but worse than
# just running the curl directly. Waiting for `use` in composite actions, e.g.
# https://github.com/actions/runner/issues/646

name: 'Neil Haskell CI'
description: 'Run standard Neil Haskell CI pattern'
inputs:
  hlint-arguments:
    description: 'Arguments to pass to HLint'
    required: false
    default: '.'
  install-fsatrace:
    description: 'Install the fsatrace binary'
    required: false
    default: false
  make-release:
    description: 'Make a release binary'
    required: false
    default: false
  github-user:
    description: 'Github user for the `neil` tool'
    required: false
    default: 'ndmitchell'
  branch:
    description: 'branch for the `neil` tool'
    required: false
    default: 'master'
runs:
  using: "composite"
  steps:
    - run: bash $GITHUB_ACTION_PATH/github.sh
      shell: bash
      env:
        HLINT_ARGUMENTS: ${{ inputs.hlint-arguments }}
        INSTALL_FSATRACE: ${{ inputs.install-fsatrace }}
        MAKE_RELEASE: ${{ inputs.make-release }}
        OS: ${{ runner.os }}
        GITHUB_USER: ${{ inputs.github-user }}
        BRANCH: ${{ inputs.branch }}
